In [1]:
import numpy as np

a = np.array([1,2,3])

a

b = np.array([[1,2,3], [4,5,6]])

b

#dimensoes
b.shape


(2, 3)

In [2]:
b[0][1]
#ou
b[0,1]

2

In [3]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [4]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [5]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [6]:
np.full((3,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.random.random((2,2))

b.shape[1]


3

In [9]:
matriz = np.zeros((6,6))

In [10]:
matriz = np.array([[(i*10)+j for j in range(6)] for i in range(6)])
matriz
#ou
for i in range(6):
    for j in range(6):
        matriz[i][j] = i * 10 + j 
        
matriz

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [11]:
x = [i for i in range(100)]

In [12]:
z = x[5:77:2]

np.array(z)


array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
       73, 75])

In [13]:

d = x[5:81:5]
np.array(d)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

In [14]:
nome = 'Lucas Ricciardi de Salles'

f = nome[1:-3:3]
f

'usiiddS'

In [15]:
f_reverso = f[::-1]
f_reverso

'Sddiisu'

In [16]:
matriz[4:6,4:6]

array([[44, 45],
       [54, 55]])

In [17]:
matriz[2:5:2,:5:2]

array([[20, 22, 24],
       [40, 42, 44]])

In [18]:
matriz[:1, 3:5]

array([[3, 4]])

In [19]:
matriz[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [20]:
matriz[[1,1],[1,2]]

array([11, 12])

In [21]:
matriz[[[1,1,1],
        [2,2,2]],
       [[1,2,4],
        [1,3,4]]]

array([[11, 12, 14],
       [21, 23, 24]])

In [22]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [23]:
np.array([1,2,3], dtype=np.float64)

array([1., 2., 3.])

In [24]:
x= np.array([
    [1,2],
    [3,4]
])

y = np.array([
    [5,6],
    [7,8]
])

In [25]:
np.add(x,y)
#ou
x+y

array([[ 6,  8],
       [10, 12]])

In [26]:
np.subtract(x,y)
#ou
x-y

array([[-4, -4],
       [-4, -4]])

In [27]:
#elemento a elemento
x*y
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [28]:
#multiplicação clássica de matriz - projeçao (nessa o shape da coluna da primeira deve ser igual ao shape das linhas da segunda)
np.dot(x,y)
#ou
x@y

array([[19, 22],
       [43, 50]])

In [73]:
#outra forma de instanciar
a,b = np.array([[1,2,3],[3,2,1]]), np.array([[5,6,7],[7,8,9]]) 

In [74]:
#exponenciação
a**2

array([[1, 4, 9],
       [9, 4, 1]])

In [75]:
a**(1/2)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 1.41421356, 1.        ]])

In [78]:
#transposta
a.T
#ou
a.transpose()

array([[1, 3],
       [2, 2],
       [3, 1]])

In [32]:
m = np.array([
    [1,2,5,6],
    [3,4,7,8]
])

In [33]:
#soma todos os elementos
np.sum(m)

m.shape

(2, 4)

In [34]:
#reduz as linhas, ou seja, transforma numa só somando os elementos da primeira linha com o da segunda 
np.sum(m, axis = 0)

array([ 4,  6, 12, 14])

In [35]:
#reduz as colunas, ou seja, transforma numa só somando os elementos da primeira coluna com o da segunda 
np.sum(m, axis = 1)

array([14, 22])

In [36]:
teste = np.random.random((4,5))

In [37]:
teste

array([[0.52361422, 0.57892542, 0.99892306, 0.1638117 , 0.29870397],
       [0.40671047, 0.55135914, 0.82299859, 0.99950567, 0.07848798],
       [0.91974672, 0.97734416, 0.71226198, 0.13359478, 0.94739944],
       [0.56170162, 0.63879979, 0.08644247, 0.09602131, 0.25777528]])

In [38]:
j = teste[2,:]
j

array([0.91974672, 0.97734416, 0.71226198, 0.13359478, 0.94739944])

In [39]:
#erro, pois coluna de j != de linhas da m
j@teste

ValueError: shapes (5,) and (4,5) not aligned: 5 (dim 0) != 4 (dim 0)

In [ ]:
#ok, pois numero de colunas de teste igual ao numero de colunas
teste@j

In [66]:
h = np.random.random((2,5,6,9,3,5))
h.shape
#vamos reduzir até ficar uma 2x9

(2, 5, 6, 9, 3, 5)

In [67]:
h = np.sum(h, axis=5)
h.shape

(2, 5, 6, 9, 3)

In [68]:
h = np.sum(h, axis=4)
h.shape

(2, 5, 6, 9)

In [69]:
h = np.sum(h, axis=2)
h.shape

(2, 5, 9)

In [70]:
#PRONTO!
h = np.sum(h, axis=1)
h.shape

(2, 9)